language: generic
sudo: required
services:
  - docker

// before the test are run
before_install:
  - docker build -t luismiguel464/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luismiguel464/docker-react npm run test
